[package]
name = "corrode_playground"
version = "0.1.0"
authors = ["Edgardo Hames <ehames@gmail.com>", "Francisco Ferreira <fferreira@gmail.com>"]

[dependencies]
nickel = "0.8"
tempfile = "2.1"
rustc-serialize = "0.3"
log = "0.3"
env_logger="0.4"
